CircleCI-Public/slack-orb

src/@orb.yml

I found this in combination with `apk add bash curl` works on alpine based images.

Remove $SHELL check and prefer run option

---

src/@orb.yml

merge lint fixes into my branch

:scissors: Remove trailing whitespace to fix lint build :nail_care:

---

src/@orb.yml

using image spotify/alpine (can change this to an alpine image from circleci if needed and available). This is also changing the shell-check from using $SHELL to $BASH as suggested in issue #16.

Adding job for notifying about awaiting approval

---

.circleci/config.yml
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
src/examples/approval.yml
src/examples/notify.yml

- use newest orb-tools jobs
- fix approval-notification job
- add PR & issue templates

Fix notify example

---

.circleci/config.yml
README.md
src/commands/status.yml

https://github.com/CircleCI-Public/slack-orb/pull/36

Copy include_* options from notify to status => master

---

.circleci/config.yml
LICENSE
README.md
src/commands/approval.yml
src/commands/notify.yml
src/commands/status.yml

https://github.com/CircleCI-Public/slack-orb/pull/40
thanks @fumikony !!

Support here,channel,everyone mentions => master

---

src/examples/approval.yml
src/examples/notify.yml
src/examples/status.yml

https://github.com/CircleCI-Public/slack-orb/issues/42
folks get confused when our examples have older SemVers than whatever the most recent release version is
change all SemVers in examples to `x.y.z`, to make more clear that it is just an example

Iynere examples versions

---

.circleci/config.yml
README.md

https://github.com/CircleCI-Public/slack-orb/pull/45

Iynere examples versions => master

---

.circleci/config.yml
README.md
src/commands/notify-on-failure.yml
src/commands/status.yml
src/examples/status.yml

https://discuss.circleci.com/t/can-slack-orb-use-multiple-only-for-branch-strings
folks are turning to an outdated community slack orb b/c this one doesn't support multiple branches for status messages
copy logic from `clir/slack-orb@0.0.6`

Multiple branches status

---

.github/PULL_REQUEST_TEMPLATE.md

grammar correction

---

.github/ISSUE_TEMPLATE/Support.md

- [x ] README has been updated, if necessary
added support template

added template

---

.github/ISSUE_TEMPLATE/Support.md
.github/ISSUE_TEMPLATE/bug.md
.github/PULL_REQUEST_TEMPLATE.md
LICENSE
README.md
src/commands/approval.yml
src/commands/notify.yml
src/commands/status.yml
src/examples/notify.yml
src/jobs/approval-notification.yml

Skip CI for now to ensure the correct semver is used. Will manually create a minor update.

Accumulation of several hacktoberfest updates [skip ci]

---

src/commands/approval.yml
src/commands/notify.yml
src/commands/status.yml

Fixes #25 
Using the which utility checking if cURL exists, if it does the code returned is 0 else the code returned is 1 by the command, Which we then check with grep and in case of 1 we exit and echo `curl not installed`

Fix check curl exists

---

src/executors/default.yml

Add cimg/base as default executor.

---

.circleci/config.yml
README.md
src/commands/approval.yml
src/commands/notify.yml
src/commands/status.yml
src/examples/notify.yml

Closes #51: Mention triggering user
Uses @Supernats idea of using environment variables to map the GitHub username and Slack user id ([here](https://github.com/CircleCI-Public/slack-orb/issues/51#issuecomment-495278671_)).

51 custom mention

---

.circleci/config.yml
README.md
src/commands/approval.yml
src/commands/notify.yml
src/commands/status.yml
src/examples/notify.yml

Reverts CircleCI-Public/slack-orb#98
Received a failure in this build: https://circleci.com/gh/CircleCI-Public/slack-orb/1334
Reverting and then inspecting further.

Revert "51 custom mention"

---

README.md

- [X ] README has been updated, if necessary
While looking at ways to integrate CircleCI with Slack, I found the table a little wonky to look at.
Removed 1 line from md file so that table would be formatted correctly.

Fix for small table bug in readme [semver:skip]

---

.circleci/config.yml
src/commands/notify.yml
src/message_templates/basic_fail_1.json
src/scripts/notify.sh

4dot0mentions

---

README.md

Approval command has [8 params](https://github.com/CircleCI-Public/slack-orb/blob/7b8b587cf6ef938ee495821065a93b182ead0249/src/commands/approval.yml#L3-L45), but some params not in README.
Add description of some parameters to README

[semver:skip] [Doc] Add missing parameters in README

---

.circleci/config.yml
README.md
src/scripts/notify.sh

Support macos integration testing

4dot0 macos testing

---

.circleci/config.yml
src/scripts/notify.sh
src/tests/notify.bats

Moves away from using the channel-scoped incoming webhook.

Use Slack access token over incoming webhook

---

.circleci/config.yml
README.md
src/commands/notify.yml
src/examples/custom_notification.yml
src/examples/full_deployment_sample.yml
src/examples/notify_on_fail_with_template.yml
src/examples/on_hold_notification.yml
src/examples/only_notify_on_branch.yml
src/examples/successful_tagged_deployment.yml
src/scripts/notify.sh

- Add shellchecking
- POSIX compliant
- Alpine testing
- Add On-Hold workflow
- Add wiki links to readme

4dot0 api testing

---

.circleci/config.yml
README.md
src/examples/custom_notification.yml
src/examples/full_deployment_sample.yml
src/examples/notify_on_fail_with_template.yml
src/examples/on_hold_notification.yml
src/examples/only_notify_on_branch.yml
src/examples/successful_tagged_deployment.yml
src/scripts/notify.sh

Reverts CircleCI-Public/slack-orb#175

Revert "4dot0 api testing"

---

.circleci/config.yml
src/scripts/notify.sh

4dot0 posix improvements

---

src/@orb.yml
src/commands/notify.yml
src/examples/notify_two_channels.yml

Description Updates

---

README.md

Added links to usage examples on CircleCI developer page

[semver:skip] Include usage examples links

---

src/examples/successful_tagged_deployment.yml
src/scripts/notify.sh

Fixes #200 - Incorrect parameter value for event.
Fixes #185 - Improved error messaging for missing required values.

[semver:patch] Usage example update

---

README.md
src/commands/notify.yml
src/scripts/notify.sh
src/tests/notify.bats

Added a filter pattern by the current tag.
Closes #192 and #187

Filter patterns by current branch and/or current tag [semver:minor]

---

src/scripts/notify.sh
src/tests/notify.bats

[semver:patch] Decide earlier whether to post message

---

README.md
src/commands/notify.yml
src/scripts/notify.sh

Changes:
++ New parameter `ignore_errors` of type `boolean`
Description:
> Ignore errors posting to Slack.
> Disable to catch initial setup errors. Re-enable to prevent Slack errors from affecting your pipeline.

[semver:minor] New Feature: Exit_On_Fail

---

src/@orb.yml

Update the orb description to mention Arm64 V8 compatibility

[semver:patch][WEB-119] Update description to mention platform compatibility

---

src/scripts/notify.sh

Fixes https://github.com/CircleCI-Public/slack-orb/issues/258

Make nounset compatible [semver:minor]

---

src/scripts/notify.sh

Handle CIRCLE_TAG not being set

---

src/message_templates/basic_success_1.json

* Add mentions to basic_success_1 template, for a similar usecase
like in the basic_fail_1 template.
See: https://github.com/CircleCI-Public/slack-orb/issues/285

Add mentions to basic_success_1.json

---

src/scripts/notify.sh

I believe this PR should close #276.

[semver:minor] #276 bugfix: added escaping of \\ and `

---

.circleci/config.yml
src/commands/notify.yml
src/jobs/on-hold.yml
src/scripts/notify.sh

added debug param to view api call to slack and response

Added debug params [semver:patch]

---

src/message_templates/basic_fail_1.json
src/message_templates/basic_on_hold_1.json
src/message_templates/basic_success_1.json
src/message_templates/success_tagged_deploy_1.json
src/scripts/notify.sh

removed extra literal \n in slack message templates

[semver: patch] Fix message templates

---

src/examples/successful_tagged_deployment.yml

Fix: template used in example [semver:patch]

---

src/scripts/notify.sh

Fix: Change jq source to avoid errors with package managers [semver:minor]

---

src/commands/notify.yml

Add wiki reference for the env variables SLACK_ACCESS_TOKEN and SLACK_DEFAULT_CHANNEL [semver:patch]

---

src/scripts/notify.sh

Closes #338 .
This PR changes how the debug parameter is checked.

fix: debug parameter always on

---

.circleci/config.yml
.circleci/test-deploy.yml
src/scripts/notify.sh

- Remove all exclusions from shellcheck.
- Replace filters with anchors where applicable.
- Fix shellcheck errors that were hidden by exclusions.

fix: shellcheck errors and remove exclusions from config

---

src/scripts/notify.sh

- Prevent job from running if host OS is Windows (closes #358)

feat: exit if host OS is Windows

---

.circleci/test-deploy.yml
src/commands/notify.yml
src/jobs/on-hold.yml

- Add a new parameter to allow customization of the step name.
- Properly name all tests to differentiate them.

feat: add the `step_name` parameter

---

src/scripts/notify.sh

- Replace grep's flag to support Alpine.

fix: replace `--quiet` with `-q` in grep to support Alpine

---

.circleci/test-deploy.yml
src/scripts/notify.sh
src/tests/notify.bats

Closes #264
- Replace all occurrences of `"` with `\"`.

fix: escape double quotes

---

.circleci/config.yml
.circleci/test-deploy.yml

Noticed the github machine user bot wasnt operating here.

ci: add bot comments to pr

---

src/@orb.yml

Include Windows in the list of supported OS.

chore: add Windows in the list of supported OS

---

src/message_templates/success_tagged_deploy_1.json

Adding field to mention user on success_tagged_deploy template

Update success_tagged_deploy template

---

src/jobs/on_hold.yml

Closes #406 
- Mention POSIX expressions as a requirement in the parameter description.

refactor: improve pattern parameter description

---

README.md

So it can wrap and can be read without scrolling horizontally

README.md: Remove code block around paragraph

---

.circleci/config.yml
.circleci/test-deploy.yml
README.md
src/commands/notify.yml
src/examples/scheduled_scheduled.yml
src/scripts/main.sh
src/scripts/notify.sh
src/scripts/utils.sh

This is an updated version of the PR #453.
I'm adding tests, and updating the script to be compatible with Mac and Alpine.
I had to update the shell to bash for this to work

feat: add scheduling messages (#453)

---

src/commands/notify.yml
src/jobs/on-hold.yml
src/scripts/notify.sh

Enable bash debug mode when the commands enable debug.
This would solve #416

Enable bash debug mode when debug is true

---

.circleci/config.yml
.circleci/test-deploy.yml
README.md
src/commands/notify.yml
src/examples/scheduled_scheduled.yml
src/scripts/main.sh
src/scripts/notify.sh
src/scripts/utils.sh

Reverts CircleCI-Public/slack-orb #463

Set bash as default again

---

.circleci/test-deploy.yml
src/commands/notify.yml
src/commands/reaction.yml

This add a parameter to identify when the command is going to be executed in a windows environment.
This is a breaking change for windows users as the current fix is removed, now all windows users needs to add the parameter

Windows parameter
