- src/orb.yml
Hello there @iynere and @eddiewebb,
I'm having the same issue described here: [issues/2](https://github.com/CircleCI-Public/slack-orb/issues/2). The problem happens because the env **$SLACK_WEBHOOK** is always checked, even when the parameter **webhook** is set.
What do you think about this solution? Is there a better way to fix it?
Thanks!
> fix issue when using the webhook parameter

- src/@orb.yml
Self-explanatory -- if a job succeeds or fails it would be good to report *which* job it was.
> Add job name to default message on Success/Fail hooks

- src/@orb.yml
Backticks are escaping/removing the job name in the @orb.yaml default message.
Sorry about that -- was going for the slack formatting but I think this is an unsupported interaction in their API
> Remove Backticks (incorrectly escaping the job name)

- README.md
- src/@orb.yml
Added a new parameter - `only_for_branch` - to the `slack/notify` command, which allows slack updates to be triggered for builds on a specific branch only.
Fixes https://github.com/CircleCI-Public/slack-orb/issues/17
> Added option to trigger notifications on a specific branch

- src/@orb.yml
at the moment, the curl commands that invoke the slack API are formatted as a single-line command, making it harder to read / follow, especially with all the escaped quotes, etc. 
I think splitting this into multi-line, properly-indented json makes it much easier to follow / maintain / spot any issues.
> improve formatting for `curl` commands

- README.md
- src/commands/status.yml
We want to use project name rather than $CIRCLE_JOB in our messages.
Also see issue #33 where @cayter says they want custom messages for the status command.
Add new `success_message` and `failure_message` parameters to `status` command, defaulting to existing hardcoded values for those messages.
> Support custom success/failure messages for slack/status

- README.md
- src/commands/status.yml
We do a lot of deployments across a lot of environments and while the status updates are valuable, they are currently very verbose. We would like them to fit on a single line.
Copied include_* from notify to status command
> Copy include_* options from notify to status

- .circleci/config.yml
- README.md
- src/commands/approval.yml
- src/commands/notify.yml
- src/commands/status.yml
We want to use `@here` in mentions.
Add support for channel mentions: `@here`, `@channel` and `@everyone`.
> Support here,channel,everyone mentions

- .circleci/config.yml
- src/commands/approval.yml
- src/commands/notify.yml
- src/commands/status.yml
pull request #40 breaks normal mentions if slack user ids include `here`, `channel` or `everyone`.
- fix the pattern for `grep -E`.
- add a test.
> fix mentions

- src/commands/status.yml
Fixes #47
In the current implementation, using `failure_message` in status doesn't
affect the `fallback` field.
It causes a problem when sending a message to bots such as `hubot-slack`.
The `hubot-slack` parses the `fallback` field if a message has an attachment.
We should set `text` and `fallback` field to the same value.
The `success_message` also have the same issue. So I fixed both.
Any feedback is welcome!
> commands/status: Set success_message / failure_message to fallback field

- .yamllint
- publish-alpha.sh
- src/@orb.yml
- src/commands/notify-on-failure.yml
- src/commands/status.yml
- src/examples/status.yml
We use this command a lot, and everywhere we essentially repeat the
following over and over. It would be great if the orb just provided it
for us!
```
orbs:
slack: circleci/slack@2.5.1
commands:
slack-notify-on-failure:
steps:
- slack/status:
fail_only: "true"
only_for_branch: "master"
```
> Wrap `status` command with sensible defaults

- src/commands/status.yml
some lines are super long, its unintuitive / confusing imo to have `description` fields come before `type` & `default` in a parameter definition
just some cosmetic restructuring to make code more readable on GH
> improve code readability in status command

- src/commands/status.yml
#64 
The `slack/status` command supports custom success/failure messages from #37, but currently these messages do not include the mentions while the default messages do. So this pull request fixes it to include the mentions in the custom messages as well.
> Add mentions in custom messages of status command

- README.md
Fix only_for_branches parameter name in the example
> Fix parameter name in the example

- README.md
- src/commands/approval.yml
- src/commands/notify.yml
- src/commands/status.yml
This change solves #66 
Check for the existence of the required /bin/bash executable directly rather than trying to infer it from an env var named `$BASH` which will not be set in the `/bin/sh` shell on Alpline, and probably some other distros.
> Fix bash check

- README.md
- src/commands/approval.yml
- src/commands/notify.yml
- src/commands/status.yml
- src/examples/notify.yml
refs #53 
Slack webhook has `channel` parameter passed by POST data.
It overrides slack channel configured when webhook created.
With this, we can make notification for various channel with single webhook url.
<!---
why is this change required? what problem does it solve?
paste links to any relevant GitHub issues filed against
this repository that this pull request addresses
--
> Add `channel` parameter for overring webhook's default

- README.md
- src/commands/approval.yml
- src/commands/notify.yml
- src/commands/status.yml
- [ ✓] All new jobs, commands, executors, parameters have descriptions
- [ ✓] Examples have been added for any significant new features
- [ ✓] README has been updated, if necessary
#105 
According to my understanding, after exploring this repo & slack api, channel parameter must be described as **channel ID** for avoiding any user misunderstanding of inputs & resulting any unnecessary errors. So, i have updated channel parameter description as channel ID in all jobs, commands, examples etc.
> channel parameter is described concisely.

- README.md
- src/commands/approval.yml
- src/jobs/approval-notification.yml
This addresses an inconsistency, where the project and job number fields can't be suppressed when sending an approval message, as they can in other contexts.
Let me know if there's a way to auto-generate the `README` (there should be if there isn't!), or if you want me to squash to one commit. Since the docs were missing entirely, I made two separate commits.
* Support suppressing `include_project_field` and `include_job_number_field` for the `approval` command and `approval-notification` job, similar to what's supported for other commands
* Add missing docs for the above types, including information about the new parameters
> feat: Allow suppressing certain fields for approvals

- LICENSE
The copyright information included in the `LICENSE` file is incorrect and should be "Circle Internet Services, Inc." compared to the other Orb repos.
> Change Copyright to Circle Internet Services, Inc.

- README.md
- src/jobs/approval-notification.yml
This just gives parity with the feature added in #67 to support overriding the channel for the approval command (and other commands)
* Add the ability to set the channel override in the approval-notification job and pass it through to the approval command (where the channel override was added in #67)
> feat: Add channel param to approval-notification

- README.md
- src/commands/notify.yml
Adds support for `image_url` passed to `notify` in order to attach an image to the notification message.
Reference CircleCI-Public/slack-orb#78
> Add support for image_url on notifications

- README.md
- src/commands/notify.yml
To be able to show an icon next to the notification user in slack :)
We currently cannot customize the icon for the "incoming-webhook"
> Notify command: added new author_icon parameter

- src/scripts/notify.sh
See https://github.com/CircleCI-Public/slack-orb/issues/194
I found it challenging to debug the permission issues I experienced when integrating with the `slack-orb` notify command. I believe including the `curl` output in the console, or parsing the response and showing a helpful error  in the CI console may be worth considering.
Lemme know what you think. Many thanks 🙏
> [feat] include curl response in CI output [semver:patch]

- src/scripts/notify.sh
Accidentally / erroneously removed this in a previous commit. Required for detecting job status. Repaired and added a comment for future reference.
> [semver:patch] Fix job status detection

- src/message_templates/basic_fail_1.json
- src/message_templates/basic_on_hold_1.json
- src/message_templates/basic_success_1.json
- src/message_templates/success_tagged_deploy_1.json
Currently, Slack notifications for any messages sent by this Orb are displayed as follows
It makes for a bad user experience since their first notification from the Slack orb is an error message. 
This PR fixes the "_this content cant be displayed._" message to a more descriptive text. 
According to the Slack [docs](https://api.slack.com/messaging/composing/layouts#add_blocks_array), adding a `text` field when using `blocks` can prevent this message. 
> When you're using blocks in your message payload, the top-level text field becomes a fallback message displayed in notifications. Blocks should define everything else about the desired visible message.
> Add text field for descriptive Slack notifications [semver:patch]

- src/scripts/notify.sh
`SLACK_WEBHOOK` is no longer supported; instead, `SLACK_ACCESS_TOKEN` and `SLACK_PARAM_CHANNEL` are used. We've been checking for those first, and bailing if they're not found. But people upgrading to 4.x won't understand the error they see about a missing `SLACK_ACCESS_TOKEN`.
Instead, check for and warn about `SLACK_WEBHOOK` first to make it clear why more setup is required.
(Source: Tried to upgrade, was confused. 😉 )
> Check for SLACK_WEBHOOK before SLACK_ACCESS_TOKEN [semver:patch]

- src/message_templates/basic_success_1.json
The basic_success_1 template doesn't escape newlines properly. Update it
to match the others (basically `s/\n/\\n/`). I see it was like this at
one point, but then the `\\n` were changed to `\n` at some point. I'm
guessing since we don't have problems with the other templates and they
all use the `\\n` format, that it should be using `\\n`.
maybe
Fixes #255
> [semver:patch] fix: update basic success newline escaping

- src/commands/notify.yml
Per @chrisbruford's [suggestion](https://github.com/CircleCI-Public/slack-orb/issues/219#issuecomment-758829230) in #219, this change will make it a little more clear what is expected in the _template_ parameter. I am also including the built-in templates wiki and dynamic template links for users to reference.
> Chore: Updated "template" parameter description to make its function more clear [semver:patch]

- src/scripts/notify.sh
Closes #256 by appending the notification message body and response to `/tmp/slack-orb/logs/post-to-slack.json` for every `slack/notify` step. Example:
Given:
```
...
- slack/notify:
template: basic_fail_1
mentions: "@orbs"
event: always
...
```
`/tmp/slack-orb/logs/post-to-slack.json` will contain:
```
[
{
"slackMessageBody": {
"text": "CircleCI job failed.",
"blocks": [...],
"channel": "potato"
},
"slackSentResponse": {
"ok": true,
"channel": "potato",
"ts": "1642183316.024400",
"message": {
"type": "message",
"subtype": "bot_message",
"text": "CircleCI job failed.",
"ts": "1642183316.024400",
"username": "ThePotatoMaster",
"bot_id": "bot_id",
"blocks": [...]
},
"warning": "missing_charset",
"response_metadata": {
"warnings": [
"missing_charset"
]
}
}
}
]
```
> Feat: Provide additional logging for debugging issues [semver:minor]

- src/scripts/notify.sh
We've been using the slack orb in our team repository, and noticed an issue that the notify script failed with `sudo: no password was provided` error. This is because, the root user has configured the password. 
Build URL: https://app.circleci.com/pipelines/github/circleci/mongo-config-management/3287/workflows/3be9fc63-2298-4d9c-82ff-3a5418851a25/jobs/5206
We want to avoid using `sudo` on the runner executor, so I've changed the notify script to override the SUDO variable by the environment variable. Also, added some small fixes.
- remove `export`. There is no reason to use export here. In shell script, a variable is in the global scope as default.
- override SUDO if there is a `SUDO` environment variable
- remove unnecessary spaces
> Update notify.sh to add a option to override SUDO variable [semver:patch]

- src/scripts/notify.sh
When calling slack notify via the orb or in a command, using `$BASH_ENV` doesn't seem to work. Adding this explicit call lets others continue to customize the command via `$BASH_ENV` and have those customizations change the slack behavior.
Testing Results (links internal to CircleCI org):
- [job](https://app.circleci.com/pipelines/github/circleci/server/21570/workflows/40b18d91-30b6-4b4b-bfbd-555542335cc1/jobs/75332) (defined in [this branch](https://github.com/circleci/server/compare/main...repro/RE-1507)) showing the `$SLACK_PARAM_MENTIONS` being set in `$BASH_ENV`, but not being read by the `slack/notify` command correctly for the [slack post]()
- [job](https://app.circleci.com/pipelines/github/circleci/server/21821/workflows/3c823a3c-e5d9-447a-814d-a7ba035d1cf7/jobs/76872) showing …
> (RE-1507) Add explicit $BASH_ENV execution

- src/commands/notify.yml
- src/scripts/notify.sh
With this change, the `notify` command will only save the request payload and response if the `debug` parameter is set to `true`.
This PR also modifies how we handle log creation. Before, we were appending new entries to a single log file. Now we are keeping them more concise and simple to handle by splitting requests and payload into different files and generating new directories for each `slack/notify` command.
> Restrict logs creation to when the debug flag is set to true [semver:patch]

- src/commands/notify.yml
- src/message_templates/basic_on_hold_1.json
Hi, there.
I'm using CircleCI through CircleCI Server in my company. The `basic_on_hold_1.json` message template has hardcoded the CircleCI host. I've added an optional parameter that enables change it. Thank you.
1. add `circleci_host` optional parameter to `notify.yml` command
1. use it in `notify.sh` -> `basic_on_hold_1.json` template
> feat: add circleci_host param option

- src/jobs/on-hold.yml
- while the circleci_host parameter was added to the notify command, it isn't being passed through from the on-hold job
> feat: passthrough circleci_host in on-hold job

- src/scripts/notify.sh
By having the branch filtering before environment variables check, the users won't have the job failing when they don't mean to execute it in the first place.
Closes #252.
This PR changes the order of function execution in the orb. The `ShouldPost` will be the first function to execute, and if it matches non-execution pattern, it will prevent jobs from failing because of unset environment variables.
> fix: check branch pattern before env vars

- .circleci/test-deploy.yml
- src/commands/notify.yml
- src/jobs/on-hold.yml
- src/scripts/notify.sh
Closes #269.
This PR adds a new `invert-match` parameter to the `notify` command. If set to true, the parameter includes the `--invert-match` or `-v` flag in grep.
> feat: add match inversion for branch and tag patterns

- .circleci/config.yml
- .circleci/test-deploy.yml
- src/jobs/on-hold.yml
- src/scripts/notify.sh
- src/tests/notify.bats
First off - thanks for adding the `invert_match` param in the last release. This makes dealing with notifications for unknown branch names much easier. Unfortunately, in its current state it only works if you have a single pattern in the `branch_pattern` pattern. This is due to the "match fast" logic with the `break` when a match occurs. When inverting this logic, we need to ensure that ALL of the patterns don't match instead of ANY.
Example:
```yaml
branch_pattern: 'foo,bar,baz'
invert_match: true
```
If we're currently deploying the "baz" branch, "foo" does not match, so with `invert_match` true, `FLAG_MATCHES_FILTER` gets set to true, the `for`-loop is exited and the slack notification is incorrectly sent.
This PR simplifies the logic by only taking into account whether or not …
> Fix invert_match to work with multiple branch patterns

- .circleci/config.yml
- src/scripts/notify.sh
- src/tests/notify.bats
- Group conditionals and add `\` to properly break the line.
- Add the `bats` orb to run unit tests.
- Replace `==` with `=~` in the test 13.
> fix: invert match conditionals and bats tests

- .circleci/test-deploy.yml
- src/scripts/notify.sh
- src/tests/notify.bats
- Replace new line with literal `\n` in strings inside the template.
> fix: escape new line in multiline strings

- .circleci/test-deploy.yml
- src/scripts/notify.sh
- src/tests/notify.bats
Closes #279 
- Add backslashes to the list of characters to be sanitized in environment variables.
- Remove `git` dependency from integration tests since Alpine doesn't have it.
- Improve sanitization unit tests by adding "Expected vs Actual" output in case of failure.
> fix: escape backslashes

- .circleci/test-deploy.yml
- src/scripts/notify.sh
- Closes #382
- Include `|| true` after the `variable_names` grep to ensure it won't exit.
This ensures grep will succeed even if nothing matches. Thus solving the issue of sub-shells failing the sanitization function.
- Include a condition to exit the function if `variable_names` is empty.
This prevents the function from running without variable names to sanitize.
> fix: sanitization error with sub-shells

- .circleci/test-deploy.yml
Resolve error in testing on Mac due to outdated certificates in the test job environment, breaking CURL.
> ci: update macos and docker

- .circleci/config.yml
- .circleci/test-deploy.yml
- src/examples/full_deployment_sample.yml
- src/examples/on_hold_notification.yml
- src/jobs/on_hold.yml
This PR updates the Slack Orb to the new major version of Orb Tools. As it contains breaking changes, several modifications were unnecessary to move from v11 to [v12](https://circleci.com/developer/orbs/orb/circleci/orb-tools). 
The comprehensive list of changes can be found below.
1. Update the orb-tools version from 11.4 to 12.0.
1. Remove the `orb-tools/publish` job since development versions are no longer necessary.
1. Move the job requirement list from `orb-tools/publish` to `orb-tools/continue`.
1. Rename the `orb-tools/continue` job parameters to comply with the new snake case standard.
- `orb_name`, `pipeline_number` and `vcs_type`.
1. Add the new `orb_name` parameter in `orb-tools/continue`.
1. Update the orb-tools version from 11.4 to 12.0.
1. Remove the `slack: …
> ci: migrate to Orb Tools 12

- src/commands/notify.yml
Description:
This is a fix for the latest thread message posting capability.
Motivation:
There is a misbehaviour when there is a Slack message posted but the pipeline fails. In these occasions, if a user initiates a  "Rerun from failed" and the failed job actually passes and the pipeline gets to the slack job, intended to post a message in a thread, the message will be posted as a new one.
This is because of the way the cache key is formed (`{{ .Environment.CIRCLE_WORKFLOW_ID }}`) which is different when rerunning the pipeline.
This PR adds another cache key to be relied on in such scenarios. It will now be falling back to using the git revision, which will be the same with every rerun of the pipeline.
Checklist:
[x] All new jobs, commands, executors, parameters have descriptions.
[ ] …
> fix: re-running pipelines

- src/commands/notify.yml
Right now, if the event type is `fail`, the `thread_id` will be ignored because the `save_cache` and `restore_cache` steps do not have `when` set, meaning they default to `on_success` and do not run.
This PR changes the cache steps so that they always run (on the condition that `thread_id` is being set, anyway).
> fix: `thread_id` cache should work for all event types

- README.md
- src/commands/notify.yml
- src/examples/scheduled_scheduled.yml
- src/scripts/notify.sh
This pull request add a new parameter `scheduled_offset_seconds` to the `notify` command. This parameter has a default value of 0.
If not 0, `notify.sh` script will call [chat.scheduleMessage](https://api.slack.com/methods/chat.scheduleMessage) instead of [chat.postMessage](https://api.slack.com/methods/chat.postMessage)
> feat: add scheduling messages (#452)

- .circleci/test-deploy.yml
- src/scripts/notify.sh
- src/tests/notify.bats
- src/tests/sampleVariableWithCRLF.txt
This pull request fixes the issue where variables used within a custom template contain CRLF-style new lines (ie `\r\n`).
A fix and test are added to test against this using a file with multiline content set to use `CRLF` for line endings.
A production use case for this issue is when one wants to send a Slack notification with a multiline commit message from GitHub. If the message was fetched using `git show --pretty=format:%B --no-patch`, the new lines uses `\r\n`.
> fix: add removal of carriage return during sanitization

- .circleci/test-deploy.yml
- src/jobs/on-hold.yml
As indicated in #451 the on-hold job doesn't support the thread_id parameter, it makes sense to have it, as the on-hold job is just a call to the notify command and both should offer the same capabilities.
> Add thread_id to on-hold job

- README.md
- src/commands/notify.yml
In #461 it is indicated that the default patterns are causing an issue when the tag is always evaluated and failed to send the notification. Removing the default value would fix this by only evaluating when a pattern is set explicitly.
> Remove default values for tag and branch patterns

- src/commands/notify.yml
- src/scripts/notify.sh
I'm adding a retry to the notify command as requested in #426
> Add a retry option to the notify command

- .circleci/test-deploy.yml
- src/scripts/notify.sh
- src/tests/generate-payload.js
Resolves #468
Allows to pass environment variables to the parameters Template and custom, this evaluation is only done when the value starts with $ to ensure it is a variable, otherwise it would cause issues.
> Add string substitution to template and custom parameters

- src/commands/notify.yml
- src/scripts/notify.sh
- src/scripts/utils.sh
- src/tests/notify.bats
Slack attaches a preview if a link or a media URL is included as part of the message by default as described in [the documentation](https://api.slack.com/reference/messaging/link-unfurling)
The following changes makes this behavior optional as it is supported by the API.
* Adds a new set of parameters in the `notify` command.
* Those parameters are sent to the `notify.sh` script.
* Adds a couple of tests to review the message generation.
Testing message with and without unfurl:
Closes #479
> Added Unfurl Links and Media properties
